// ترجمات المركز القانوني العالمي
window.translations = {
    ar: {
        // القائمة
        "nav.home": "الرئيسية",
        "nav.services": "خدماتنا",
        "nav.team": "فريقنا",
        "nav.updates": "التحديثات",
        "nav.contact": "اتصل بنا",
        
        // القسم الرئيسي
        "hero.title": "المركز القانوني العالمي",
        "hero.subtitle": "الخبرة القضائية مع الحلول القانونية المبتكرة",
        "hero.description": "نحن لا نقدم مجرد استشارات قانونية، بل نمنحكم حلولاً متكاملة تضمن حماية حقوقكم",
        "hero.cta": "تواصل معنا الآن",
        
        // الخدمات
        "services.title": "خدماتنا القانونية",
        "services.subtitle": "نخبة من المتخصصين بقيادة المستشار محمد عبد الجواد",
        "services.1.title": "قانون الشركات",
        "services.1.description": "تأسيس الكيانات القانونية وحوكمة الاستثمارات",
        "services.2.title": "محكمة النقض",
        "services.2.description": "طعون الجنايات والمدني مذكرات قانونية دقيقة",
        "services.3.title": "القانون الدولي",
        "services.3.description": "توثيق زواج الأجانب وإجراءات الإقامة",
        
        // الفريق
        "team.title": "فريقنا القانوني",
        "team.contact": "تواصل عبر واتساب",
        "team.1.position": "المحامي بالنقض والإدارية العليا",
        "team.1.description": "المؤسس والمدير التنفيذي للمركز القانوني العالمي",
        
        // التحديثات
        "updates.title": "التحديثات القانونية",
        "updates.subtitle": "أبرز التعديلات التشريعية في القوانين المصرية",
        
        // الاتصال
        "contact.title": "اتصل بنا",
        "contact.subtitle": "تواصل مع المركز القانوني",
        "contact.whatsapp": "واتساب",
        "contact.email": "البريد الإلكتروني",
        "contact.map.title": "موقعنا",
        "contact.map.description": "دار السلام، القاهرة",
        "contact.map.button": "افتح الخريطة",
        
        // الفوتر
        "footer.description": "حلول قانونية احترافية",
        "footer.copyright": "© 2025 المركز القانوني العالمي"
    },
    en: {
        "nav.home": "Home",
        "nav.services": "Services",
        "nav.team": "Our Team",
        "nav.updates": "Updates",
        "nav.contact": "Contact Us",
        "hero.title": "Global Legal Center",
        "hero.subtitle": "Judicial Expertise with Innovative Legal Solutions",
        "hero.description": "We don't just offer legal advice, we provide integrated solutions",
        "hero.cta": "Contact Us Now",
        "services.title": "Our Legal Services",
        "services.subtitle": "Elite specialists led by Counselor Mohamed Abdel Gawad",
        "services.1.title": "Corporate Law",
        "services.1.description": "Establishing legal entities and investment governance",
        "services.2.title": "Court of Cassation",
        "services.2.description": "Criminal and civil appeals with accurate legal memoranda",
        "services.3.title": "International Law",
        "services.3.description": "Documentation of foreign marriages and residency procedures",
        "team.title": "Our Legal Team",
        "team.contact": "Contact via WhatsApp",
        "team.1.position": "Attorney at Cassation and Supreme Administrative Courts",
        "team.1.description": "Founder and Executive Director of Global Legal Center",
        "updates.title": "Legal Updates",
        "updates.subtitle": "Key legislative amendments in Egyptian laws",
        "contact.title": "Contact Us",
        "contact.subtitle": "Contact the Legal Center",
        "contact.whatsapp": "WhatsApp",
        "contact.email": "Email",
        "contact.map.title": "Our Location",
        "contact.map.description": "Dar El Salam, Cairo",
        "contact.map.button": "Open Map",
        "footer.description": "Professional Legal Solutions",
        "footer.copyright": "© 2025 Global Legal Center"
    },
    fr: {
        "nav.home": "Accueil",
        "nav.services": "Services",
        "nav.team": "Notre Équipe",
        "nav.updates": "Mises à Jour",
        "nav.contact": "Contactez-nous",
        "hero.title": "Centre Juridique Mondial",
        "hero.subtitle": "Expertise Judiciaire avec Solutions Juridiques Innovantes",
        "hero.description": "Nous ne proposons pas seulement des conseils juridiques",
        "hero.cta": "Contactez-nous Maintenant",
        "services.title": "Nos Services Juridiques",
        "services.subtitle": "Spécialistes d'élite dirigés par le Conseiller Mohamed Abdel Gawad",
        "services.1.title": "Droit des Sociétés",
        "services.1.description": "Création d'entités juridiques et gouvernance des investissements",
        "services.2.title": "Cour de Cassation",
        "services.2.description": "Appels criminels et civils avec mémoires juridiques précises",
        "services.3.title": "Droit International",
        "services.3.description": "Documentation des mariages étrangers et procédures de résidence",
        "team.title": "Notre Équipe Juridique",
        "team.contact": "Contact via WhatsApp",
        "team.1.position": "Avocat à la Cour de Cassation et aux Cours Administratives Suprêmes",
        "team.1.description": "Fondateur et Directeur Exécutif du Centre Juridique Mondial",
        "updates.title": "Mises à Jour Juridiques",
        "updates.subtitle": "Amendements législatifs clés dans les lois égyptiennes",
        "contact.title": "Contactez-nous",
        "contact.subtitle": "Contactez le Centre Juridique",
        "contact.whatsapp": "WhatsApp",
        "contact.email": "E-mail",
        "contact.map.title": "Notre Emplacement",
        "contact.map.description": "Dar El Salam, Le Caire",
        "contact.map.button": "Ouvrir la Carte",
        "footer.description": "Solutions Juridiques Professionnelles",
        "footer.copyright": "© 2025 Centre Juridique Mondial"
    },
    it: {
        "nav.home": "Home",
        "nav.services": "Servizi",
        "nav.team": "Il Nostro Team",
        "nav.updates": "Aggiornamenti",
        "nav.contact": "Contattaci",
        "hero.title": "Centro Legale Globale",
        "hero.subtitle": "Competenza Giudiziaria con Soluzioni Legali Innovative",
        "hero.description": "Non offriamo solo consulenza legale",
        "hero.cta": "Contattaci Ora",
        "services.title": "I Nostri Servizi Legali",
        "services.subtitle": "Specialisti d'élite guidati dal Consigliere Mohamed Abdel Gawad",
        "services.1.title": "Diritto Societario",
        "services.1.description": "Costituzione di entità legali e governance degli investimenti",
        "services.2.title": "Corte di Cassazione",
        "services.2.description": "Appelli penali e civili con memoriali giuridici precisi",
        "services.3.title": "Diritto Internazionale",
        "services.3.description": "Documentazione di matrimoni stranieri e procedure di residenza",
        "team.title": "Il Nostro Team Legale",
        "team.contact": "Contatto via WhatsApp",
        "team.1.position": "Avvocato presso la Corte di Cassazione e le Corti Amministrative Supreme",
        "team.1.description": "Fondatore e Direttore Esecutivo del Centro Legale Globale",
        "updates.title": "Aggiornamenti Legali",
        "updates.subtitle": "Emendamenti legislativi chiave nelle leggi egiziane",
        "contact.title": "Contattaci",
        "contact.subtitle": "Contatta il Centro Legale",
        "contact.whatsapp": "WhatsApp",
        "contact.email": "Email",
        "contact.map.title": "La Nostra Posizione",
        "contact.map.description": "Dar El Salam, Il Cairo",
        "contact.map.button": "Apri Mappa",
        "footer.description": "Soluzioni Legali Professionali",
        "footer.copyright": "© 2025 Centro Legale Globale"
    },
    de: {
        "nav.home": "Startseite",
        "nav.services": "Dienstleistungen",
        "nav.team": "Unser Team",
        "nav.updates": "Aktualisierungen",
        "nav.contact": "Kontakt",
        "hero.title": "Globales Rechtszentrum",
        "hero.subtitle": "Juristische Expertise mit Innovativen Rechtslösungen",
        "hero.description": "Wir bieten nicht nur Rechtsberatung",
        "hero.cta": "Jetzt Kontaktieren",
        "services.title": "Unsere Rechtsdienstleistungen",
        "services.subtitle": "Elitespezialisten unter der Leitung von Berater Mohamed Abdel Gawad",
        "services.1.title": "Gesellschaftsrecht",
        "services.1.description": "Gründung juristischer Einheiten und Investitionssteuerung",
        "services.2.title": "Kassationsgericht",
        "services.2.description": "Straf- und Zivilbeschwerden mit präzisen rechtlichen Schriftsätzen",
        "services.3.title": "Internationales Recht",
        "services.3.description": "Dokumentation ausländischer Ehen und Aufenthaltsverfahren",
        "team.title": "Unser Rechtsteam",
        "team.contact": "Kontakt über WhatsApp",
        "team.1.position": "Rechtsanwalt beim Kassationsgericht und bei den Obersten Verwaltungsgerichten",
        "team.1.description": "Gründer und Geschäftsführer des Globalen Rechtszentrums",
        "updates.title": "Rechtliche Aktualisierungen",
        "updates.subtitle": "Wichtige gesetzliche Änderungen in ägyptischen Gesetzen",
        "contact.title": "Kontaktieren Sie uns",
        "contact.subtitle": "Kontaktieren Sie das Rechtszentrum",
        "contact.whatsapp": "WhatsApp",
        "contact.email": "E-Mail",
        "contact.map.title": "Unser Standort",
        "contact.map.description": "Dar El Salam, Kairo",
        "contact.map.button": "Karte Öffnen",
        "footer.description": "Professionelle Rechtslösungen",
        "footer.copyright": "© 2025 Globales Rechtszentrum"
    }
};